# Generated by Django 3.1.3 on 2020-11-13 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Transmutation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=2047)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('quantity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reality.quantity')),
            ],
        ),
        migrations.CreateModel(
            name='Cooktsu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooktsu_green', to='reality.transmutation', unique=True)),
                ('ingredients', models.ManyToManyField(to='reality.Ingredient')),
                ('orange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooktsu_orange', to='reality.transmutation', unique=True)),
                ('red', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooktsu_red', to='reality.transmutation', unique=True)),
                ('yellow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooktsu_yellow', to='reality.transmutation', unique=True)),
            ],
        ),
    ]
