# Generated by Django 3.1.3 on 2020-11-13 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooktsu',
            name='alchemy_name',
            field=models.CharField(default='', max_length=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cooktsu',
            name='name',
            field=models.CharField(default='', max_length=23),
            preserve_default=False,
        ),
    ]
