# Generated by Django 3.1.3 on 2020-11-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0002_auto_20201114_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='element',
            field=models.CharField(choices=[('red', 'Terre'), ('orange', 'Eau'), ('green', 'Air'), ('yellow', 'Feu')], default=('red'), max_length=7),
        ),
    ]
