# Generated by Django 3.1.3 on 2020-11-14 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0003_ingredient_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='element',
            field=models.CharField(choices=[('red', 'Terre'), ('orange', 'Eau'), ('green', 'Air'), ('yellow', 'Feu')], default='red', max_length=7),
        ),
    ]
