# Generated by Django 3.1.3 on 2020-11-14 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0004_auto_20201114_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooktsu',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='reality/cooktsu/'),
        ),
    ]
