# Generated by Django 3.1.3 on 2020-11-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reality', '0005_cooktsu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooktsu',
            name='description',
            field=models.TextField(default='', max_length=2047),
            preserve_default=False,
        ),
    ]
