# Generated by Django 3.1.3 on 2021-02-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poety', '0002_auto_20201109_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnapHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1023)),
            ],
        ),
        migrations.AddField(
            model_name='snappoety',
            name='history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='poety.snaphistory'),
        ),
    ]
