# Generated by Django 3.1.3 on 2021-02-14 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poety', '0003_auto_20210214_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='snaphistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snaphistory',
            name='description',
            field=models.TextField(default='', max_length=1023),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snaphistory',
            name='name',
            field=models.SlugField(max_length=63, unique=True),
        ),
    ]
