# Generated by Django 3.1.3 on 2021-02-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poety', '0004_auto_20210214_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='snaphistory',
            name='slug',
            field=models.SlugField(default='', max_length=63, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snaphistory',
            name='name',
            field=models.CharField(max_length=63, unique=True),
        ),
    ]
