# Generated by Django 3.1.3 on 2021-02-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poety', '0005_auto_20210214_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snaphistory',
            name='name',
            field=models.CharField(max_length=63),
        ),
    ]
